### ISSUE TITLE
Update manifesto language to be stronger.

### ISSUE THREAD

**Issue by jaekwon** [virgo-project/virgo#7]
TODO: https://thebulletin.org/current-issue/

Nov 2019: "In this issue, top experts examine technology-related doomsdays the world might soon face if they go unaddressed, not to frighten readers, but to alert them, so they might act in time, making a loud and unmistakable demand: that the Earth be preserved, that the human experiment be extended, that midnight never toll."

**Comment by jaekwon** [comment]
I suggest we pull all the best language, and cite them all in a link from the manifesto.
In the spirit of Kopimism, copy as much as possible, and provide citations for origins.

**Comment by nestmiron** [comment]
I suggest the use of the Earth Charter principles (https://earthcharter.org/discover/the-earth-charter) as a reference for further development and refinement of the Manifesto. We are amid of an ecocide and running short of time. The Charter could help us speed things up.

Some excerpts from the Earth Charter:

“The choice is ours: form a global partnership to care for Earth and one another or risk the destruction of ourselves and the diversity of life.”

“We have the knowledge and technology to provide for all and to reduce our impacts
on the environment. The emergence of a global civil society is creating new opportunities to build a democratic and humane world.”

“Affirm that with increased freedom, knowledge, and power comes increased responsibility to promote the common good.”

“Build democratic societies that are just, participatory, sustainable, and peaceful.”

“Promote the development, adoption, and equitable transfer of environmentally sound technologies.”

“Recognize the ignored, protect the vulnerable, serve those who suffer, and enable them to develop their capacities and to pursue their aspirations.”

“Ensure that economic activities and institutions at all levels promote human development in
an equitable and sustainable manner.”

“Strengthen democratic institutions at all levels, and provide transparency and accountability
in governance, inclusive participation in decision making, and access to justice.”

“…we must find ways to harmonize diversity with unity, the exercise of freedom with the common good, short-term objectives with long-term goals. Every individual, family, organization, and community has a vital role to play.”

**Comment by nestmiron** [comment]
“We are living through the Great Acceleration – a unique event in the 4.5 billion-year history of our planet – with exploding human population and economic growth driving unprecedented planetary change through the increased demand for energy, land and water. This is so great that many scientists believe we are entering a new geological epoch, the Anthropocene. Yet the human benefits of the Great Acceleration have only been possible with nature. Without healthy natural systems we need to ask whether future human development is even possible.”
– Living Planet Report 2018, https://www.worldwildlife.org/pages/living-planet-report-2018

“Even today’s technology and knowledge can reduce considerably the human impact on ecosystems. They are unlikely to be deployed fully, however, until ecosystem services cease to be perceived as free and limitless, and their full value is taken into account.” 
– Millenium Ecosystem Assessment, https://www.millenniumassessment.org/en/BoardStatement.html

“Indeed, the attempt to live according to the notion that the fragments are really separate is, in essence, what has led to the growing series of extremely urgent crises that is confronting us today. Thus, as is now well known, this way of life has brought about pollution, destruction of the balance of nature, over-population, world-wide economic and political disorder, and the creation of an overall environment that is neither physically nor mentally healthy for most of the people who have to live in it.”
― David Bohm, [Wholeness and the Implicate Order](https://www.amazon.com/Wholeness-Implicate-Order-David-Bohm/dp/0415289793/ref=sr_1_1?crid=24WJB0B59OVE8&keywords=wholeness+and+the+implicate+order&qid=1573129895&sprefix=wholeness+and+the+implicate+or%2Caps%2C236&sr=8-1)

“Goals for conserving and sustainably using nature and achieving sustainability cannot be met by current trajectories, and goals for 2030 and beyond may only be achieved through transformative changes across economic, social, political and technological factors.” 
– IPBES, https://www.ipbes.net/global-assessment-report-biodiversity-ecosystem-services

“We are the first generation that has a clear picture of the value of nature and the enormous impact we have on it. We may also be the last that can act to reverse this trend. From now until 2020 will be a decisive moment in history.”
 – Living Planet Report 2018, https://www.worldwildlife.org/pages/living-planet-report-2018

**Comment by jpatten314** [comment]
Hey Jae Kwon,

I had some thoughts about the manifesto. Here is a different argumentative structure for your manifesto that could perhaps be integrated with the current one (with #5 being another way of framing Virgo’s approach):

1.	Climate change is an issue that threatens every landscape on Earth–environmental degradation does not respect human-made borders. Pollution travels across them with ease. Environmental destruction committed by industrialized nations directly impacts people on the other side of the planet.
2.	Unfortunately, borders constrain our ability to problem-solve climate change. Conversations are generally concerned with what individual governments can do to curb emissions. These policies have mostly failed because no nation is willing to take the first step. The infrastructure does not exist at this time for renewable energies to supplant fossil fuel usage and permit the current levels of economic activity. Carbon controls would create a drag on the economic competitiveness of nations. Therefore, the correct long-term course of action scores no points for politicians looking for short-term victories. Multilateral accords like the Paris Agreement fail for similar reasons. Large industrialized nations have one foot out the door, unwilling to be beholden to an agreement that competitor nation-states are unlikely to respect.
3.	The solution to climate change needs to be borderless. It needs to represent a global democracy in which people are united not by citizenship, but by joint ownership of the earth. We each bear the consequences of climate change. Current generations suffer forest fires, poor air quality, and food shortages. Future generations will encounter these calamities on a greater scale as well as other terrifying and unprecedented consequences. These disasters will be felt across the world, from Bangladesh to Beijing to Los Angeles.
4.	The conversation should focus on borderless collectives capable of creating global solutions. These include market solutions (renewable energy technologies, energy efficiency technologies), cultural solutions (denser housing, sustainable agriculture, greater STEM opportunities), and political solutions (new economic opportunities in the developing world, empowerment of women). We should ask questions like, what systems foster borderless climate solutions? What structures catalyze the global dissemination of ideas, technologies, and capital for the purpose of environmental stewardship? What structures create the communication channels by which to coordinate these efforts?
5.	The Virgo DAO is an imperfect starting point for decentralized problem-solving. It is imperfect by virtue of its singularity. The DAO will achieve its goal when it becomes greatly outnumbered by other decentralized, borderless collectives, each contributing significant capital and community to the common goal. The Virgo DAO is not meant to be the sole ecosystem for conversations like this. It is a minor spiral, a singular arm of the ever-growing cosmos of global citizenship.
